/* tslint:disable:max-line-length */
export default {
    'brodsmuler-dittnav': 'Ditt NAV',
    'brodsmuler-dittsykefravaer': 'Ditt sykefravær',
    'brodsmuler-tiltak': 'Tiltak',
    'fleretiltak-header': 'Det finnes flere alternativer',
    'fleretiltak-lenke': 'Se oversikt over mulighetene.',
    'fleretiltak-passedeg': 'NAV har flere tilbud som kan hjelpe deg ut i jobb.',
    'tittel-utenarbeidsgiver': 'Trenger du hjelp for å komme i jobb?',
    'tittel-hararbeidsgiver': 'Trenger du hjelp for å komme tilbake i jobb?',
    'ingress-utenarbeidsgiver': 'Av og til kan man trenge litt ekstra for å komme i jobb. Snakk med oss, så kan vi sammen finne ut hva som passer for deg.',
    'ingress-hararbeidsgiver': 'Hvilken situasjon ønsker du å være i etter sykmeldingsperioden? Ut fra det du svarer, viser vi deg noen alternativer.',
    'ingress-maal-samme-stilling': 'Jeg er tilbake i samme jobb hos arbeidsgiveren min.',
    'ingress-maal-samme-arbeidsgiver': 'Jeg er tilbake i en tilpasset eller ny stilling hos arbeidsgiveren min.',
    'ingress-maal-ny-arbeidsgiver': 'Jeg er i jobb hos en ny arbeidsgiver.',
    'ingress-maal-usikker': 'Jeg er usikker.',
    'informasjon-totiltak': 'Her er to alternativer:',
    'kontaktenav-lenke-underoppfolging': 'Gå til aktivitetsplanen',
    'kontaktenav-snakkmednav': 'Snakk med oss om muligheter',
    'kontaktenav-takontakt-ikkeunderoppfolging': 'Ta gjerne kontakt med NAV-kontoret ditt hvis du vil snakke om hvilke muligheter du har. Du kan også sende en melding til veilederen din når du er inne i aktivitetsplanen din på nav.no.',
    'kontaktenav-takontakt-underoppfolging': 'Ta gjerne kontakt med NAV-kontoret ditt hvis du vil snakke om hvilke muligheter du har. Du kan også sende en melding til veilederen din når du er inne i aktivitetsplanen din på nav.no.',
    'tiltak-lonnstilskudd-tittel': 'Lønnstilskudd',
    'tiltak-lonnstilskudd-hva': 'Vet du om en arbeidsgiver som er interessert i å ansette deg? Trenger du litt tid for å komme i gang for fullt? NAV kan dekke deler av lønnen din en stund. Du vurderer sammen med arbeidsgiveren og veilederen din hvor mye NAV skal dekke.',
    'tiltak-lonnstilskudd-lesmer': 'Les mer om lønnstilskudd',
    'tiltak-oppfolging-tittel': 'Oppfølging',
    'tiltak-oppfolging-hva': 'Du kan få veiledning og hjelp til å søke jobb. Kanskje du trenger mer kompetanse eller hjelpt til noen praktiske oppgaver? Ofte kan det også gjøres noen tilpasninger på arbeidsplassen. Du kan få oppfølging både mens du søker og i startfasen etter at du har fått jobb.',
    'tiltak-oppfolging-lesmer': 'Les mer om oppfølging',
    'tiltak-tilrettelegging-tittel': 'Tilrettelegging',
    'tiltak-tilrettelegging-hva': 'Du kan få hjelp til å vurdere arbeidsplassen din. Kanskje du kan fortsette i samme jobb hvis den blir tilrettelagt for dine behov? Du kan få hjelpemidler, eller arbeidsgiveren din kan få tilskudd for å legge til rette for deg.',
    'tiltak-tilrettelegging-lesmer': 'Les mer om tilrettelegging',
    'tiltak-arbeidsrettet-rehabilitering-tittel': 'Arbeidsrettet rehabilitering',
    'tiltak-arbeidsrettet-rehabilitering-hva': 'Vil du gjerne komme i jobb, men trenger hjelp til å mestre helsen din? Du kan få tilpasset hjelp og råd fra flinke fagfolk, slik at du likevel kan fungere i jobb.',
    'tiltak-arbeidsrettet-rehabilitering-lesmer': 'Les mer om arbeidsrettet rehabilitering',
    'tiltak-mentor-tittel': 'Mentor',
    'tiltak-mentor-hva': 'NAV kan gi støtte til en mentor når du skal begynne i en ny stilling på din arbeidsplass. Mentoren er gjerne en kollega  som kan hjelpe deg både faglig og sosialt.',
    'tiltak-mentor-lesmer': 'Les mer om mentor',
    'tiltak-opplaering-tittel': 'Opplæring',
    'tiltak-opplaering-hva': 'Trenger du nye kunnskaper for å få en annen stilling på din arbeidsplass? Du kan få korte, yrkesrettede kurs som NAV arrangerer med praktisk og teoretisk opplæring. Også annen opplæring eller utdanning kan være aktuelt.',
    'tiltak-opplaering-lesmer': 'Les mer om opplæring',
    'tiltak-avklaring-tittel': 'Avklaring',
    'tiltak-avklaring-hva': 'Er det lenge siden du var i jobb, eller har helsen din blitt dårligere? Trenger du å bli tryggere på hva du kan jobbe med? Du kan få hjelp til å finne ut hvilke jobber du trives med og mestrer.',
    'tiltak-avklaring-lesmer': 'Les mer om avklaring',
};