/* tslint:disable:max-line-length */
export default {
    'brodsmuler-dittnav': 'Ditt NAV',
    'brodsmuler-dittsykefravaer': 'Ditt sykefravær',
    'brodsmuler-tiltak': 'Tiltak',
    'fleretiltak-header': 'Det finnes flere alternativer',
    'fleretiltak-lenke': 'Se oversikt over mulighetene.',
    'fleretiltak-passedeg': 'NAV har flere tilbud som kan hjelpe deg ut i jobb.',
    'tittel-utenarbeidsgiver': 'Trenger du hjelp for å komme i jobb?',
    'tittel-hararbeidsgiver': 'Trenger du hjelp for å komme tilbake i jobb?',
    'ingress-utenarbeidsgiver': 'Av og til kan man trenge litt ekstra for å komme i jobb. Snakk med oss, så kan vi sammen finne ut hva som passer for deg.',
    'ingress-hararbeidsgiver': 'Hvilken situasjon ønsker du å være i etter sykmeldingsperioden? Ut fra det du svarer, viser vi deg noen alternativer.',
    'ingress-maal-1': 'Jeg er tilbake i samme jobb hos arbeidsgiveren min.',
    'ingress-maal-2': 'Jeg er tilbake i en tilpasset eller ny stilling hos arbeidsgiveren min.',
    'ingress-maal-3': 'Jeg er i jobb hos en ny arbeidsgiver.',
    'ingress-maal-4': 'Jeg er usikker.',
    'informasjon-totiltak': 'Her er to alternativer:',
    'kontaktenav-lenke-underoppfolging': 'Gå til aktivitetsplanen',
    'kontaktenav-snakkmednav': 'Snakk med oss om muligheter',
    'kontaktenav-takontakt-ikkeunderoppfolging': 'Ta gjerne kontakt med NAV-kontoret ditt hvis du vil snakke om hvilke muligheter du har. Du kan også sende en melding til veilederen din når du er inne i aktivitetsplanen din på nav.no.',
    'kontaktenav-takontakt-underoppfolging': 'Ta gjerne kontakt med NAV-kontoret ditt hvis du vil snakke om hvilke muligheter du har. Du kan også sende en melding til veilederen din når du er inne i aktivitetsplanen din på nav.no.',
    'tiltak-lonnstilskudd-tittel': 'Lønnstilskudd',
    'tiltak-lonnstilskudd-hva': 'Vet du om en arbeidsgiver som er interessert i å ansette deg? Trenger du litt tid for å komme i gang for fullt? NAV kan dekke deler av lønnen din en stund. Du vurderer sammen med arbeidsgiveren og veilederen din hvor mye NAV skal dekke.',
    'tiltak-lonnstilskudd-lesmer': 'Les mer om lønnstilskudd',
    'tiltak-oppfolging-tittel': 'Oppfølging',
    'tiltak-oppfolging-hva': 'Du kan få veiledning og hjelp til å søke jobb. Kanskje du trenger mer kompetanse eller hjelpt til noen praktiske oppgaver? Ofte kan det også gjøres noen tilpasninger på arbeidsplassen. Du kan få oppfølging både mens du søker og i startfasen etter at du har fått jobb.',
    'tiltak-oppfolging-lesmer': 'Les mer om oppfølging',
};